// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace STS.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210602145704_BrandAndStoreManagements")]
    partial class BrandAndStoreManagements
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Hotline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Data.Entities.BrandManager", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Username1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Username");

                    b.HasIndex("BrandId");

                    b.HasIndex("Username1");

                    b.ToTable("BrandManagers");
                });

            modelBuilder.Entity("Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Data.Entities.ShiftAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("MealEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MealStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<int?>("ShiftReferenceId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("StaffUsername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ShiftReferenceId");

                    b.HasIndex("SkillId");

                    b.HasIndex("StaffUsername");

                    b.HasIndex("StoreId");

                    b.ToTable("ShiftAssignment");
                });

            modelBuilder.Entity("Data.Entities.ShiftRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PreferSkill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("StaffUsername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeekScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StaffUsername");

                    b.HasIndex("WeekScheduleId");

                    b.ToTable("ShiftRegister");
                });

            modelBuilder.Entity("Data.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("Data.Entities.Staff", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Username1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Username");

                    b.HasIndex("BrandId");

                    b.HasIndex("Username1");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Data.Entities.StaffScheduleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxHours")
                        .HasColumnType("int");

                    b.Property<int>("MinHours")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("StaffUsername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WeekScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StaffUsername");

                    b.HasIndex("WeekScheduleId");

                    b.ToTable("StaffScheduleDetail");
                });

            modelBuilder.Entity("Data.Entities.StaffSkill", b =>
                {
                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("StaffUsername")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StaffId", "SkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("StaffUsername");

                    b.ToTable("StaffSkill");
                });

            modelBuilder.Entity("Data.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrandId1")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId1");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Data.Entities.StoreManager", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("Username1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Username");

                    b.HasIndex("BrandId");

                    b.HasIndex("StoreId");

                    b.HasIndex("Username1");

                    b.ToTable("StoreManagers");
                });

            modelBuilder.Entity("Data.Entities.StoreStaff", b =>
                {
                    b.Property<string>("StaffId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StoreId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrimaryStore")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StoreId1")
                        .HasColumnType("int");

                    b.HasKey("StaffId", "StoreId");

                    b.HasIndex("StoreId1");

                    b.ToTable("StoreStaff");
                });

            modelBuilder.Entity("Data.Entities.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Password")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Username");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Data.Entities.WeekSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("WeekSchedule");
                });

            modelBuilder.Entity("Data.Entities.WeekScheduleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("WeekScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WorkStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("WeekScheduleId");

                    b.ToTable("WeekScheduleDetail");
                });

            modelBuilder.Entity("Data.Entities.BrandManager", b =>
                {
                    b.HasOne("Data.Entities.Brand", "Brand")
                        .WithMany("BrandManagers")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("Username1");

                    b.Navigation("Brand");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.ShiftAssignment", b =>
                {
                    b.HasOne("Data.Entities.ShiftAssignment", "ShiftReference")
                        .WithMany()
                        .HasForeignKey("ShiftReferenceId");

                    b.HasOne("Data.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Staff", "Staff")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("StaffUsername");

                    b.HasOne("Data.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShiftReference");

                    b.Navigation("Skill");

                    b.Navigation("Staff");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Data.Entities.ShiftRegister", b =>
                {
                    b.HasOne("Data.Entities.Staff", "Staff")
                        .WithMany("ShiftRegisters")
                        .HasForeignKey("StaffUsername");

                    b.HasOne("Data.Entities.WeekSchedule", "WeekSchedule")
                        .WithMany("ShiftRegisters")
                        .HasForeignKey("WeekScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("WeekSchedule");
                });

            modelBuilder.Entity("Data.Entities.Skill", b =>
                {
                    b.HasOne("Data.Entities.Brand", "Brand")
                        .WithMany("Skills")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Data.Entities.Staff", b =>
                {
                    b.HasOne("Data.Entities.Brand", "Brand")
                        .WithMany("Staff")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("Username1");

                    b.Navigation("Brand");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.StaffScheduleDetail", b =>
                {
                    b.HasOne("Data.Entities.Staff", "Staff")
                        .WithMany("StaffScheduleDetails")
                        .HasForeignKey("StaffUsername");

                    b.HasOne("Data.Entities.WeekSchedule", "WeekSchedule")
                        .WithMany("StaffScheduleDetails")
                        .HasForeignKey("WeekScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("WeekSchedule");
                });

            modelBuilder.Entity("Data.Entities.StaffSkill", b =>
                {
                    b.HasOne("Data.Entities.Skill", "Skill")
                        .WithMany("StaffSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Staff", "Staff")
                        .WithMany("StaffSkills")
                        .HasForeignKey("StaffUsername");

                    b.Navigation("Skill");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Data.Entities.Store", b =>
                {
                    b.HasOne("Data.Entities.Brand", "Brand")
                        .WithMany("Stores")
                        .HasForeignKey("BrandId1");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Data.Entities.StoreManager", b =>
                {
                    b.HasOne("Data.Entities.Brand", null)
                        .WithMany("StoreManagers")
                        .HasForeignKey("BrandId");

                    b.HasOne("Data.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("Username1");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.StoreStaff", b =>
                {
                    b.HasOne("Data.Entities.Staff", "Staff")
                        .WithMany("StoreStaffs")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Store", "Store")
                        .WithMany("StoreStaffs")
                        .HasForeignKey("StoreId1");

                    b.Navigation("Staff");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Data.Entities.User", b =>
                {
                    b.HasOne("Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Data.Entities.WeekSchedule", b =>
                {
                    b.HasOne("Data.Entities.Store", "Store")
                        .WithMany("WeekSchedules")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Data.Entities.WeekScheduleDetail", b =>
                {
                    b.HasOne("Data.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.WeekSchedule", "WeekSchedule")
                        .WithMany("WeekScheduleDetails")
                        .HasForeignKey("WeekScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("WeekSchedule");
                });

            modelBuilder.Entity("Data.Entities.Brand", b =>
                {
                    b.Navigation("BrandManagers");

                    b.Navigation("Skills");

                    b.Navigation("Staff");

                    b.Navigation("StoreManagers");

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("Data.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Data.Entities.Skill", b =>
                {
                    b.Navigation("StaffSkills");
                });

            modelBuilder.Entity("Data.Entities.Staff", b =>
                {
                    b.Navigation("ShiftAssignments");

                    b.Navigation("ShiftRegisters");

                    b.Navigation("StaffScheduleDetails");

                    b.Navigation("StaffSkills");

                    b.Navigation("StoreStaffs");
                });

            modelBuilder.Entity("Data.Entities.Store", b =>
                {
                    b.Navigation("StoreStaffs");

                    b.Navigation("WeekSchedules");
                });

            modelBuilder.Entity("Data.Entities.WeekSchedule", b =>
                {
                    b.Navigation("ShiftRegisters");

                    b.Navigation("StaffScheduleDetails");

                    b.Navigation("WeekScheduleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
